### ISSUE TITLE
Template names need documentation

### ISSUE THREAD

**Issue by mjreich** [nxus/web#39]
Need to document template names and how to override.  Both prefixing (which is covered in the opts section), but also which templates map to which routes.  

Recommend we add a 'create' and 'edit' template for specific overriding.  Also need to document that 'form' is actually the create/edit template you want to override.

**Comment by loppear** [comment]
Agreed, with some adjustment. Potential docs:

# ViewController
## Overriding templates

Assuming your `opts.prefix`/`opts.templatePrefix` is 'my-module`, the following templates are registered with default implementations: 
 * `my-module-detail`
 * `my-module-list`

# EditController
## Overriding templates
See also the `ViewController` templates.
Assuming your `opts.prefix`/`opts.templatePrefix` is 'my-module`, the following templates are registered with default implementations: 
 * `my-module-create`
 * `my-module-edit`
