### ISSUE TITLE
default list page for model throws error

### ISSUE THREAD

**Issue by ScottMaxson** [nxus/web#9]
using the app-boilerplate, with updated dependencies for the latest nxus-* modules, trying out the default view page for mvc-test-item:

> Unhandled rejection ReferenceError: /media/disk2/projects/nxus4/app-boilerplate/node_modules/nxus-web/lib/templates/web-controller-list.ejs:1
>  >> 1| <%- render("actions-buttons", {actions: actions.default, makeActionUrl: function(link) {return base + link }}) %>
>     2|
>     3| <table class="table table-stripped">
>     4|     <thead>
> 
> actions is not defined

**Comment by loppear** [comment]
Diagnosis: actions only gets added to context if any actions have been added. That's probably correct still. Those render calls should be wrapped in checks for whether there are any actions.

**Comment by mjreich** [comment]
Agree - same approach as with Flash messages partial.
